### ISSUE TITLE
Doesn't work with Komodo IDE 10

### ISSUE THREAD

**Issue by drptbl** [krizoek/komodo-comment-storage#1]
After running your macro in Komodo, getting this error:

![screen shot 2016-05-18 at 17 11 13](https://cloud.githubusercontent.com/assets/8177587/15364126/9c50e2ec-1d1b-11e6-8640-49f99b123a3e.png)

**Comment by kberns** [comment]
You'll get that error if there is no comments with the smiley chars inside

A example is this:

☺No-space-123ABC-ID The Text\nNew line text ◙tag1◘ ◙tag2◘☻

As you see, it need to start with a white and end with a black smiley
